'use strict';
const { app, BrowserWindow, ipcMain } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { Controller } = require('../src/controller');
const { DemoMonitors } = require('../src/monitor/demo');
app.whenReady().then(async () => {
  const window = new BrowserWindow({ width: 432, height: 360, show: false, frame: false, webPreferences: { preload: path.resolve('src/preload.js'), contextIsolation: true, sandbox: true } });
  const errors = [];
  window.webContents.on('console-message', (_, level, message) => { if (level >= 3) errors.push(message); });
  const controller = new Controller({ adapter: new DemoMonitors(), storage: { load: () => ({}), save: () => {} }, emit: state => window.webContents.send('state', state) });
  const handlers = { 'state:get': () => controller.snapshot(), 'monitors:refresh': () => controller.refresh(), 'brightness:set': x => controller.setNow(x), 'ramp:start': x => controller.start(x), 'ramp:cancel': x => controller.cancel(x), 'schedule:add': x => controller.addSchedule(x), 'schedule:remove': x => controller.removeSchedule(x), 'schedule:toggle': x => controller.toggleSchedule(x), 'preset:apply': x => controller.preset(x), 'settings:save': x => controller.configure(x), 'window:hide': () => {} };
  for (const [name, fn] of Object.entries(handlers)) ipcMain.handle(name, (_, x) => fn(x));
  ipcMain.handle('window:resize', (_, height) => { window.setSize(window.getSize()[0], Math.min(720, Math.max(160, height))); });
  ipcMain.handle('monitors:migrate', (_, args) => controller.migrate(args));
  await controller.refresh();
  await window.loadFile(path.resolve('src/renderer/index.html'));
  const run = code => window.webContents.executeJavaScript(code);
  await new Promise(resolve => setTimeout(resolve, 300));
  assert.ok(await run("!document.querySelector('#fade-builder').open"), 'Fade starts collapsed');
  assert.ok(await run("[...document.querySelectorAll('.live-slider')].every(el=>el.getBoundingClientRect().bottom <= innerHeight)"), 'Every live slider must be visible');
  assert.ok(window.getSize()[1] <= 380, 'Default popup should be compact');
  fs.writeFileSync(path.resolve('assets/screenshot.png'), (await window.webContents.capturePage()).toPNG());
  await run("document.querySelector('[data-preset=night]').click()");
  await new Promise(resolve => setTimeout(resolve, 50));
  assert.ok(controller.monitors.every(m => m.brightness === 20));
  await run("document.querySelector('[data-tab=settings]').click(); document.querySelector('#idle-minutes').value=5; document.querySelector('#idle-enabled').checked=true; document.querySelector('#idle-enabled').dispatchEvent(new Event('change'))");
  await new Promise(resolve => setTimeout(resolve, 50));
  assert.equal(controller.settings.idleMinutes, 5);
  fs.mkdirSync('.tmp',{recursive:true});
  fs.writeFileSync('.tmp/settings.png',(await window.webContents.capturePage()).toPNG());
  await run("document.querySelector('[data-tab=schedule]').click(); document.querySelector('#new-schedule').click(); document.querySelector('#schedule-trigger').value='sunset'; document.querySelector('#schedule-trigger').dispatchEvent(new Event('change')); document.querySelector('#latitude').value=51.5; document.querySelector('#longitude').value=-0.1; document.querySelector('#schedule-form').requestSubmit()");
  await new Promise(resolve => setTimeout(resolve, 50));
  assert.equal(controller.schedules[0]?.kind, 'solar');
  assert.equal(controller.schedules[0]?.preset, 'night');
  await new Promise(resolve=>setTimeout(resolve,100));
  fs.writeFileSync('.tmp/schedules.png',(await window.webContents.capturePage()).toPNG());
  await run("document.querySelector('#new-schedule').click()");
  await new Promise(resolve=>setTimeout(resolve,100));
  fs.writeFileSync('.tmp/builder.png',(await window.webContents.capturePage()).toPNG());
  await run("document.querySelector('[data-tab=now]').click(); const slider=document.querySelector('#monitor-list input'); slider.value=55; slider.dispatchEvent(new Event('input',{bubbles:true}));");
  await new Promise(resolve => setTimeout(resolve, 200));
  assert.equal(controller.monitors[0].brightness, 55);
  assert.deepEqual(errors, []);
  for (const width of [320,375,414,768]) {
    window.setSize(width,720); await new Promise(resolve=>setTimeout(resolve,80));
    assert.ok(await run('document.documentElement.scrollWidth <= innerWidth'), `No horizontal overflow at ${width}`);
  }
  console.log('UI smoke passed: sliders visible, collapsed fade, presets, autosave, solar/preset schedules, responsive widths; screenshot saved.');
  app.quit();
}).catch(error => { console.error(error); app.exit(1); });
