'use strict';
const { app, BrowserWindow, ipcMain } = require('electron');
const fs = require('node:fs');
const path = require('node:path');
const assert = require('node:assert/strict');
const { Controller } = require('../src/controller');
const { DemoMonitors } = require('../src/monitor/demo');
app.whenReady().then(async () => {
  const window = new BrowserWindow({ width: 432, height: 648, show: false, frame: false, webPreferences: { preload: path.resolve('src/preload.js'), contextIsolation: true, sandbox: true } });
  const errors = [];
  window.webContents.on('console-message', (_, level, message) => { if (level >= 3) errors.push(message); });
  const controller = new Controller({ adapter: new DemoMonitors(), storage: { load: () => ({}), save: () => {} }, emit: state => window.webContents.send('state', state) });
  const handlers = { 'state:get': () => controller.snapshot(), 'monitors:refresh': () => controller.refresh(), 'brightness:set': x => controller.setNow(x), 'ramp:start': x => controller.start(x), 'ramp:cancel': x => controller.cancel(x), 'schedule:add': x => controller.addSchedule(x), 'schedule:remove': x => controller.removeSchedule(x), 'schedule:toggle': x => controller.toggleSchedule(x), 'preset:apply': x => controller.preset(x), 'settings:save': x => controller.configure(x), 'window:hide': () => {} };
  for (const [name, fn] of Object.entries(handlers)) ipcMain.handle(name, (_, x) => fn(x));
  await controller.refresh();
  await window.loadFile(path.resolve('src/renderer/index.html'));
  const run = code => window.webContents.executeJavaScript(code);
  await new Promise(resolve => setTimeout(resolve, 300));
  assert.ok(await run("document.querySelector('#start').getBoundingClientRect().bottom <= innerHeight"), 'Start must be visible');
  fs.writeFileSync(path.resolve('assets/screenshot.png'), (await window.webContents.capturePage()).toPNG());
  await run("document.querySelector('[data-preset=night]').click()");
  await new Promise(resolve => setTimeout(resolve, 50));
  assert.ok(controller.monitors.every(m => m.brightness === 20));
  await run("document.querySelector('[data-tab=settings]').click(); document.querySelector('#idle-minutes').value=5; document.querySelector('#settings-form').requestSubmit()");
  await new Promise(resolve => setTimeout(resolve, 50));
  assert.equal(controller.settings.idleMinutes, 5);
  await run("document.querySelector('[data-tab=schedule]').click(); document.querySelector('[data-mode=solar]').click(); document.querySelector('#latitude').value=51.5; document.querySelector('#longitude').value=-0.1; document.querySelector('#schedule-form').requestSubmit()");
  await new Promise(resolve => setTimeout(resolve, 50));
  assert.equal(controller.schedules[0]?.kind, 'solar');
  await run("document.querySelector('[data-tab=now]').click(); const slider=document.querySelector('#monitor-list input'); slider.value=55; slider.dispatchEvent(new Event('input',{bubbles:true}));");
  await new Promise(resolve => setTimeout(resolve, 200));
  assert.equal(controller.monitors[0].brightness, 55);
  assert.deepEqual(errors, []);
  console.log('UI smoke passed: action visible, presets, settings, solar schedules, live sliders; screenshot saved.');
  app.quit();
}).catch(error => { console.error(error); app.exit(1); });
